### ISSUE TITLE
bash: ./run.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by nekromoff** [ralbear/IMAPbackup#2]

**Comment by dwehrmann** [comment]
ran into the same issue and fixed it with vim/vi:
`:set ff=unix`
save & exit, the script will work. It is related to dos/unix file endings

**Comment by ralbear** [comment]
Thanks for fixing it @dwehrmann feel free to make a PR 😃

**Comment by ralbear** [comment]
I update the file to have LF endings
