### ISSUE TITLE
Syntax error when calling imapgrab.py

### ISSUE THREAD

**Issue by pahhur** [ralbear/IMAPbackup#4]
I get the following with a newly cloned imapgrab.py
(after having converted the file from dos to unix style)

```
python --version
Python 3.8.10
```
```
getmail --version
getmail 5.13

```

```
python ./imapgrab.py
  File "./imapgrab.py", line 114
    if(ig_options.debug is True): print "DEBUG_000: parsed options:\n",ig_options,"\nDEBUG: parsed arguments:\n",ig_args
                                        ^
SyntaxError: invalid syntax
```

```
 python ./imapgrab.py -l -s imap.google.com -u yyy@gmail.com -p xxx
  File "./imapgrab.py", line 114
    if(ig_options.debug is True):print "DEBUG_000: parsed options:\n",ig_options,"\nDEBUG: parsed arguments:\n",ig_args
                                       ^
SyntaxError: invalid syntax
```

Can you enlighten me, what I'm doing wrong?

**Comment by jimanjang** [comment]
It does not work for the same reason.

Please check.

**Comment by jimanjang** [comment]
Hello.

I solved this problem.

We have determined that this error occurs in Python 3 and later versions.

Try running Python version 2.

python2 imapgrab.py -d -v -f

**Comment by ralbear** [comment]
Thanks for raising this issue and finding a solution, I update the docs to specify `python2` is needed
